baseURL = 'https://github.com/F3nr1rrr/r4ven.gun.git'
languageCode = 'en-us'
title = 'r4ven.gun'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name = 'About Us'
    url = '/about/'
    weight = 1
  [[menu.main]]
    name = 'Write-ups'
    url = '/writeups/'
    weight = 2
  [[menu.main]]
    name = 'Blogs'
    url = '/blogs/'
    weight = 3
  [[menu.main]]
    name = 'Achievements'
    url = '/achievements/'
    weight = 4